// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtY3yKKu1jY_uYp_vPNmO0fXY8C28qOjY',
    appId: '1:414385050596:web:8dfdb4521d453ab4f12df1',
    messagingSenderId: '414385050596',
    projectId: 'stuntaware-65c76',
    authDomain: 'stuntaware-65c76.firebaseapp.com',
    storageBucket: 'stuntaware-65c76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBr75nyTGHJEfRCe4oKrZ2-xPW6wYIms',
    appId: '1:414385050596:android:886f9bd86e32428cf12df1',
    messagingSenderId: '414385050596',
    projectId: 'stuntaware-65c76',
    storageBucket: 'stuntaware-65c76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALc_0TyQD5kIeXO01k1JSigQzo_iylOh4',
    appId: '1:414385050596:ios:f4f845dc2e833a71f12df1',
    messagingSenderId: '414385050596',
    projectId: 'stuntaware-65c76',
    storageBucket: 'stuntaware-65c76.firebasestorage.app',
    iosBundleId: 'com.example.stuntaware',
  );

}